### ISSUE TITLE
[Bug] Incorrect handling of GET endpoints

### ISSUE THREAD

**Issue by invakid404** [harmonyland/harmony#166]
**What's the bug?**
When requesting GET API endpoints, Harmony tries to send the parameters in the body, but GET requests can't have a body.

**How do we reproduce it?**
For example, this error occurs when trying to fetch messages of a text channel (calling `fetchMessages` on a `TextChannel`)

**What should have happened?**
Instead of trying to send a GET request with a body, GET parameters should be used.

**What versions you're using?**
 - OS: Funtoo Linux
 - Deno: 1.10.2
 - Harmony: v2.0.0-rc1

**Do you have anything to tell us more about the bug?**
Relevant stacktrace:
```
error: Uncaught (in promise) TypeError: HEAD and GET requests may not have a body.
        throw new HTTPError(
              ^
    at BucketHandler.execute (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/bucket.ts:133:15)
    at async BucketHandler.execute (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/bucket.ts:143:14)
    at async BucketHandler.push (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/bucket.ts:51:14)
    at async RESTManager.make (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/manager.ts:236:12)
    at async RESTManager.get (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/manager.ts:259:12)
    at async Proxy.<anonymous> (https://deno.land/x/harmony@v2.0.0-rc1/src/rest/manager.ts:47:11)
    at async GuildTextChannel.fetchMessages (https://deno.land/x/harmony@v2.0.0-rc1/src/structures/textChannel.ts:141:19)
```

**Comment by DjDeveloperr** [comment]
Oop, that is a bug introduced when REST was reworked, before if body was passed to GET or DELETE, they were turned into Query String. I'll push fix in a bit.
