### ISSUE TITLE
[Bug] Add reaction on default (utf-8) emoji 

### ISSUE THREAD

**Issue by TendTo** [harmonyland/harmony#283]
**What's the bug?**
Using the `Message.addReaction()` function with a default emoji (utf-8) results in an error **400: bad request** by Discord

**How do we reproduce it?**
Add a reaction to a message having all the correct permissions.
Example:
```typescript
const message = await channel.send("Text message");
try {
  await message.addReaction("1️⃣");
} catch (e) {
  console.error(e);
}
```

**What should have happened?**
See the reaction added to the message

**What is actually happening?**
```
DiscordAPIError:
PUT https://discord.com/api/v9/channels/<channelId>/messages/<messageId>/reactions/1%EF%B8%8F%E2%83%A3/@me returned 400
(unknown) undefined
    at BucketHandler.execute (https://deno.land/x/harmony@v2.4.0/src/rest/bucket.ts:223:13)
    at async BucketHandler.push (https://deno.land/x/harmony@v2.4.0/src/rest/bucket.ts:54:13)
    at async RESTManager.make (https://deno.land/x/harmony@v2.4.0/src/rest/manager.ts:236:12)
    at async RESTManager.put (https://deno.land/x/harmony@v2.4.0/src/rest/manager.ts:339:12)
    at async GeneralSlashModule.gartic_phone_sondaggio (file:///D:/Programmazione/VSCode/Ciccione-bot/modules/slashCommands/generalCommands.ts:192:7)
    at async InteractionsClient._process (https://deno.land/x/harmony@v2.4.0/src/interactions/client.ts:355:7)
    at async https://deno.land/x/harmony@v2.4.0/src/interactions/client.ts:172:30
```

**What versions you're using?**
 - OS: Windows 10
 - Deno: 1.17.1
 - Harmony: 2.4.0

**Do you have anything to tell us more about the bug?**
I think the issue lies in one of the headers.  
After doing some tests, it seems that the header _"Content-Length": "0"_, added in the fetch request is the one causing the problem. If removed, everyghing seems to work fine, which is ironic considering https://github.com/denoland/deno/issues/11920
The line causing the issue is this one:
https://github.com/harmonyland/harmony/blob/fb9649899ee49b00887b2096e78540548085ce05/src/rest/request.ts#L148

**Comment by DjDeveloperr** [comment]
This is fixed on main branch, just a new release needs to be made. 
cc @Helloyunho

**Comment by DjDeveloperr** [comment]
v2.5.0 should have fixed this
