### ISSUE TITLE
[Bug] Crash on user kick

### ISSUE THREAD

**Issue by Blocksnmore** [harmonyland/harmony#351]
**What's the bug?**
Whenever someone gets kicked from a server the bot crashes with the following error:
```
error: Uncaught DiscordAPIError: 
GET /guilds/<guild>/members/<kicked> returned 404
(10007) Unknown Member
      throw new DiscordAPIError({
            ^
    at BucketHandler.execute (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/bucket.ts:224:13)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async BucketHandler.push (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/bucket.ts:55:13)
    at async RESTManager.make (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/manager.ts:236:12)
    at async RESTManager.get (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/rest/manager.ts:259:12)
    at async MemberRolesManager._resolveMemberPayload (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/managers/memberRoles.ts:22:23)
    at async MemberRolesManager.array (https://raw.githubusercontent.com/harmonyland/harmony/daca400ae9feab19604381abddbdab16aa1ede2b/src/managers/memberRoles.ts:50:17)
```

**How do we reproduce it?**
1. Create a `.env` file containing the following: `token=<your bot token>` and download [this code](https://gist.github.com/Blocksnmore/ceef4204c5559c277c12fc4287788a39).
1. Once the bot is online kick any user from a server
1. Crash

**What should have happened?**
Nothing should've happen.

**What is actually happening?**
The bot crashes

**What versions you're using?**
 - OS: Arch Linux `6.3.4-arch1-1`
 - Deno: Deno `1.33.2 (release, x86_64-unknown-linux-gnu)`
 - Harmony: Harmony commit `daca400`

**Comment by Helloyunho** [comment]
It seems like this happens because of the event `guildMemberRemove` trying to get a member object but fails to fetch the member's roles

**Comment by Helloyunho** [comment]
@Blocksnmore Can you try it with the latest commit? It works fine with the fix for me

**Comment by Blocksnmore** [comment]
> @Blocksnmore Can you try it with the latest commit? It works fine with the fix for me

The bot isn't crashing anymore so it seems to be fixed.
